export const resumeConfig = {
  name: "Phạm Quốc Hoàng (Will Pham)",
  title: "Full-Stack Developer",
  photo: "/resume/me.webp",
  intro: [
    "Hi! I'm Hoang, a Full-Stack Developer with a strong focus on WordPress. I build SEO-friendly websites from user interfaces to admin systems — custom themes, plugins, WooCommerce, hosting setup and PageSpeed optimization — with 30+ websites delivered for businesses.",
    "I also built and run Hoàn Hời, a cashback platform made with Next.js and live in production. Beyond WordPress, I work with React, Node.js and Python, and use Claude Code and Codex to ship faster.",
  ],
  contacts: [
    { icon: "address", label: "Address", value: "Ho Chi Minh City, Vietnam" },
    { icon: "phone", label: "Phone", value: "0971 955 144", href: "tel:+84971955144" },
    { icon: "mail", label: "Email", value: "hoangpham2263@gmail.com", href: "mailto:hoangpham2263@gmail.com" },
    { icon: "github", label: "GitHub", value: "hoangpham2263", href: "https://github.com/hoangpham2263" },
    { icon: "linkedin", label: "LinkedIn", value: "hoangpham2263", href: "https://www.linkedin.com/in/hoangpham2263/" },
  ],
  skills: [
    { group: "Frontend", items: ["HTML5 & CSS3 (Tailwind)", "JavaScript", "React & Next.js", "WordPress Themes & Plugins", "WooCommerce"] },
    { group: "Backend", items: ["PHP", "Node.js", "Python & Django", "MySQL, PostgreSQL & MongoDB", "REST API"] },
    { group: "Other", items: ["Git", "Docker", "CI", "Technical SEO, PageSpeed & Core Web Vitals"] },
    { group: "AI Tools", items: ["Claude Code", "Codex", "Gemini", "Prompt Engineering", "AI Agent Skills"] },
  ],
  education: [
    { period: "2021 – 2025", degree: "Bachelor in Software Engineering", school: "Duy Tan University" },
  ],
  work: [
    {
      company: "Hoàn Hời",
      logo: "",
      role: "Creator & Developer · Personal project",
      start: "2026",
      end: "Present",
      duration: "",
      location: "Ho Chi Minh City, Vietnam",
      description:
        "A cashback platform where users create tracked shopping links and get money back once orders are reconciled. Live in production at hoanhoi.com.",
      responsibilities: [
        "Build and run the product end-to-end with Next.js, from user features to the admin system.",
        "Handle deployment and operations in production.",
      ],
    },
    {
      company: "HD TechLabs Solution",
      logo: "",
      role: "Software Engineer (AI Evaluation) · Freelance",
      start: "Jul 2026",
      end: "Present",
      duration: "",
      location: "Remote",
      description:
        "Freelance work creating and reviewing advanced mathematics problems and coding benchmark tasks used to evaluate AI models.",
      responsibilities: [
        "Create and review advanced mathematics problems with verified reference solutions for evaluating AI models.",
        "Build coding benchmark tasks with reproducible Docker environments, automated tests and reference solutions.",
      ],
    },
    {
      company: "Puramu",
      logo: "/resume/puramu.svg",
      role: "Web Developer",
      start: "Feb 2025",
      end: "Jun 2026",
      duration: "1 year 4 months",
      location: "Ho Chi Minh City, Vietnam",
      description:
        "Developed and operated web and CRM systems, collaborating with third-party partners to automate management processes.",
      responsibilities: [
        "Built and customized WordPress themes and plugins for 30+ client websites based on their requirements.",
        "Optimized website performance, SEO and Core Web Vitals.",
        "Deployment & configuration: developed and deployed products across multiple platforms to meet each partner's needs.",
        "Testing & delivery: ensured product stability, reliability and performance before delivery.",
        "Troubleshooting: handled requests, analyzed root causes and promptly resolved issues.",
      ],
    },
    {
      company: "Meta Technology",
      logo: "",
      role: "Backend Intern",
      start: "Apr 2024",
      end: "Jul 2024",
      duration: "3 months",
      location: "Da Nang, Vietnam",
      description: "Participated in developing API systems, focusing on backend logic and data processing performance.",
      responsibilities: [
        "Developed APIs using Next.js to connect the frontend and backend.",
        "Built and maintained data flow between frontend and backend.",
        "Improved API performance for faster response.",
        "Found and fixed issues in the system.",
      ],
    },
    {
      company: "LiftSoft",
      logo: "/resume/liftsoft.webp",
      role: "Backend Developer",
      start: "Mar 2022",
      end: "Jun 2022",
      duration: "3 months",
      location: "Da Nang, Vietnam",
      description: "Contributed to API development and unit testing to ensure stable system performance.",
      responsibilities: [
        "Developed APIs using Django.",
        "Wrote unit tests to check functionality.",
        "Worked with databases to store and retrieve data.",
        "Fixed bugs and supported system maintenance.",
      ],
    },
  ],
};
