export const resumeConfig = {
  name: "Phạm Quốc Hoàng (Will Pham)",
  title: "Full-Stack Developer",
  photo: "/resume/me.webp",
  intro: [
    "Hi! I am Hoang, a Web Developer with a strong focus on WordPress. I build and customize WordPress websites, including themes, plugins, hosting setup, and styling with Tailwind CSS.",
    "I also have experience working with React.js, Next.js, and Node.js for more advanced features. In addition, I use Python for data crawling and automation tasks when needed.",
  ],
  contacts: [
    { icon: "address", label: "Address", value: "Ho Chi Minh City, Vietnam" },
    { icon: "phone", label: "Phone", value: "0971 955 144", href: "tel:+84971955144" },
    { icon: "mail", label: "Email", value: "hoangpham2263@gmail.com", href: "mailto:hoangpham2263@gmail.com" },
    { icon: "github", label: "GitHub", value: "hoangpham2263", href: "https://github.com/hoangpham2263" },
    { icon: "linkedin", label: "LinkedIn", value: "hoangpham2263", href: "https://www.linkedin.com/in/hoangpham2263/" },
  ],
  skills: [
    { group: "Frontend", items: ["HTML5 & CSS3 (Tailwind)", "WordPress Theme & Plugin Development", "JavaScript", "Next.js & React"] },
    { group: "Backend", items: ["Node.js", "Python", "MySQL & PostgreSQL", "PHP", "REST API"] },
    { group: "Other", items: ["Git", "Docker", "Technical SEO & PageSpeed"] },
  ],
  education: [
    { period: "2021 – 2025", degree: "Bachelor in Software Engineering", school: "Duy Tan University" },
  ],
  work: [
    {
      company: "HD TechLabs Solution",
      logo: "",
      role: "Software Engineer (AI Evaluation) · Freelance",
      start: "Jul 2026",
      end: "Present",
      duration: "",
      location: "Remote · Da Nang, Vietnam",
      description:
        "Freelance work creating and reviewing advanced mathematics problems and coding benchmark tasks used to evaluate AI models.",
      responsibilities: [
        "Create and review advanced mathematics problems with verified reference solutions.",
        "Build coding benchmark tasks with reproducible Docker environments, automated tests and reference solutions.",
      ],
    },
    {
      company: "Puramu",
      logo: "/resume/puramu.svg",
      role: "Web Developer",
      start: "Feb 2025",
      end: "Jun 2026",
      duration: "1 year 4 months",
      location: "Ho Chi Minh City, Vietnam",
      description:
        "Develop and operate web and CRM systems, collaborate with third-party partners to automate management processes, and provide flexible, scalable customization solutions to meet specific customer requirements.",
      responsibilities: [
        "Deployment & Configuration: Develop and deploy products across multiple platforms to meet the specific needs of each partner.",
        "Testing & Delivery: Participate in quality assurance to ensure product stability, reliability, and optimal performance before delivery.",
        "Troubleshooting: Handle requests, analyze root causes, and promptly resolve issues to maintain system stability and performance.",
      ],
    },
    {
      company: "Meta Technology",
      logo: "",
      role: "Backend Intern",
      start: "Apr 2024",
      end: "Jul 2024",
      duration: "3 months",
      location: "Da Nang, Vietnam",
      description: "Participated in developing API systems, focusing on backend logic and data processing performance.",
      responsibilities: [
        "Develop APIs using Next.js to connect the frontend and backend",
        "Build and maintain data flow between frontend and backend",
        "Improve API performance for faster response",
        "Find and fix issues in the system",
        "Work with team members to make sure everything runs smoothly",
      ],
    },
    {
      company: "LiftSoft",
      logo: "/resume/liftsoft.webp",
      role: "Backend Developer",
      start: "Mar 2022",
      end: "Jun 2022",
      duration: "3 months",
      location: "Da Nang, Vietnam",
      description: "Contributed to API development and unit testing to ensure stable system performance.",
      responsibilities: [
        "Develop APIs using Django",
        "Write unit tests to check functionality",
        "Work with databases to store and retrieve data",
        "Fix bugs and support system maintenance",
        "Assist in building backend features",
        "Work with team members to complete tasks",
      ],
    },
  ],
};
